sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t josephfajardo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true josephfajardo/docker-react npm run test -- --coverage

deploy:
  provider: elacticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-571372188847"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY